name: "Deploy deploy-gitactions-prueba" 
on:
  push: 
    branches: ["master"] 


jobs:
 
  deploy-gitactions-prueba:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hacemos pull del código"
      - run: echo "Correr migraciones"
      - run: echo "Generar binario"
      - run: echo "Publicar versión"

  